<?php
/**
 * BusinessDataDunsResolveResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataMill
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * /data.mill for applications
 *
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market.
 *
 * OpenAPI spec version: 1.6.4
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DataMill;

/**
 * BusinessDataDunsResolveResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Response of successful transformation request for /business-data/duns/resolve
/**
 * @package     DataMill
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BusinessDataDunsResolveResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "BusinessDataDunsResolveResponse"
     */
    public function testBusinessDataDunsResolveResponse()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "status_description"
     */
    public function testPropertyStatusDescription()
    {

    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {

    }

    /**
     * Test attribute "company_name_2"
     */
    public function testPropertyCompanyName2()
    {

    }

    /**
     * Test attribute "continent_name"
     */
    public function testPropertyContinentName()
    {

    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "country_code_3"
     */
    public function testPropertyCountryCode3()
    {

    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {

    }

    /**
     * Test attribute "house_number"
     */
    public function testPropertyHouseNumber()
    {

    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {

    }

    /**
     * Test attribute "fax_number"
     */
    public function testPropertyFaxNumber()
    {

    }

    /**
     * Test attribute "state_name"
     */
    public function testPropertyStateName()
    {

    }

    /**
     * Test attribute "state_code"
     */
    public function testPropertyStateCode()
    {

    }

    /**
     * Test attribute "ceo_name"
     */
    public function testPropertyCeoName()
    {

    }

    /**
     * Test attribute "ceo_title"
     */
    public function testPropertyCeoTitle()
    {

    }

    /**
     * Test attribute "ceo_secondary"
     */
    public function testPropertyCeoSecondary()
    {

    }

    /**
     * Test attribute "sic_code"
     */
    public function testPropertySicCode()
    {

    }

    /**
     * Test attribute "sic_description"
     */
    public function testPropertySicDescription()
    {

    }

    /**
     * Test attribute "year_started"
     */
    public function testPropertyYearStarted()
    {

    }

    /**
     * Test attribute "annual_turnover_local_currency"
     */
    public function testPropertyAnnualTurnoverLocalCurrency()
    {

    }

    /**
     * Test attribute "annual_turnover_indicator_code"
     */
    public function testPropertyAnnualTurnoverIndicatorCode()
    {

    }

    /**
     * Test attribute "annual_turnover_indicator_description"
     */
    public function testPropertyAnnualTurnoverIndicatorDescription()
    {

    }

    /**
     * Test attribute "annual_turnover_usd"
     */
    public function testPropertyAnnualTurnoverUsd()
    {

    }

    /**
     * Test attribute "net_income"
     */
    public function testPropertyNetIncome()
    {

    }

    /**
     * Test attribute "net_income_usd"
     */
    public function testPropertyNetIncomeUsd()
    {

    }

    /**
     * Test attribute "net_worth"
     */
    public function testPropertyNetWorth()
    {

    }

    /**
     * Test attribute "net_worth_usd"
     */
    public function testPropertyNetWorthUsd()
    {

    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {

    }

    /**
     * Test attribute "currency_name"
     */
    public function testPropertyCurrencyName()
    {

    }

    /**
     * Test attribute "marketability_code"
     */
    public function testPropertyMarketabilityCode()
    {

    }

    /**
     * Test attribute "marketability_description"
     */
    public function testPropertyMarketabilityDescription()
    {

    }

    /**
     * Test attribute "total_employees"
     */
    public function testPropertyTotalEmployees()
    {

    }

    /**
     * Test attribute "total_employees_indicator"
     */
    public function testPropertyTotalEmployeesIndicator()
    {

    }

    /**
     * Test attribute "total_employees_indicator_description"
     */
    public function testPropertyTotalEmployeesIndicatorDescription()
    {

    }

    /**
     * Test attribute "total_employees_physical_address"
     */
    public function testPropertyTotalEmployeesPhysicalAddress()
    {

    }

    /**
     * Test attribute "total_employees_physical_address_indicator"
     */
    public function testPropertyTotalEmployeesPhysicalAddressIndicator()
    {

    }

    /**
     * Test attribute "import_export_indicator"
     */
    public function testPropertyImportExportIndicator()
    {

    }

    /**
     * Test attribute "import_export_indicator_description"
     */
    public function testPropertyImportExportIndicatorDescription()
    {

    }

    /**
     * Test attribute "legal_form_code"
     */
    public function testPropertyLegalFormCode()
    {

    }

    /**
     * Test attribute "legal_form_description"
     */
    public function testPropertyLegalFormDescription()
    {

    }

    /**
     * Test attribute "business_structure_code"
     */
    public function testPropertyBusinessStructureCode()
    {

    }

    /**
     * Test attribute "business_structure_description"
     */
    public function testPropertyBusinessStructureDescription()
    {

    }

    /**
     * Test attribute "business_registration_number_code"
     */
    public function testPropertyBusinessRegistrationNumberCode()
    {

    }

    /**
     * Test attribute "business_registration_number_code_description"
     */
    public function testPropertyBusinessRegistrationNumberCodeDescription()
    {

    }

    /**
     * Test attribute "undeliverable_indicator"
     */
    public function testPropertyUndeliverableIndicator()
    {

    }

    /**
     * Test attribute "undeliverable_description"
     */
    public function testPropertyUndeliverableDescription()
    {

    }

    /**
     * Test attribute "financial_statement_date"
     */
    public function testPropertyFinancialStatementDate()
    {

    }

    /**
     * Test attribute "report_date"
     */
    public function testPropertyReportDate()
    {

    }

    /**
     * Test attribute "is_only_available_address"
     */
    public function testPropertyIsOnlyAvailableAddress()
    {

    }

    /**
     * Test attribute "is_subsidiary"
     */
    public function testPropertyIsSubsidiary()
    {

    }

    /**
     * Test attribute "total_employees_including_principals_indicator"
     */
    public function testPropertyTotalEmployeesIncludingPrincipalsIndicator()
    {

    }

    /**
     * Test attribute "is_out_of_business"
     */
    public function testPropertyIsOutOfBusiness()
    {

    }

}
